### ISSUE TITLE
sample code snippets have invalid ref to ZoweZLUX

### ISSUE THREAD

**Issue by philippe-richard** [zowe/workshop-starter-app#4]
when running the tutorial, i found a number of typos in chapter:
Adding your Dataservice to the App:
https://github.com/zowe/workshop-user-browser-app#adding-your-dataservice-to-the-app
the snippet of code reads:
"let uri = this.filter ? ZoweZLUX.uriBroker.pluginRESTUri....."
in fact ZoweZLUX should be replaced by rocketMVD (2 instances), otherwise npm run-script start will fail compilation with error msg:
ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts
./src/app/userbrowser-component.ts
[tsl] ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts(48,29)
     TS2304: Cannot find name 'ZoweZLUX'.

ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts
./src/app/userbrowser-component.ts
[tsl] ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts(48,156)
     TS2304: Cannot find name 'ZoweZLUX'.
There are similar issues further down the tutorial from other code snippets belonging to file userbrowser-component.ts
The same issue applies to https://github.com/zowe/workshop-starter-app.git...
in  file /X9/var/zowe/0.9.0/workshop-starter-app/webClient/src/app/workshopstarter-component.ts
All references to ZoweZLUX should be changed to RocketMVD
Also pluginManager should be changed to PluginManager

**Comment by 1000TurquoisePogs** [comment]
Same as in https://github.com/zowe/workshop-user-browser-app/issues/5, it appears the tutorial was unclear on releases of Zowe needed. So, I've created tags to clarify, where master actually is currently intended to work on zowe 0.9.1: https://github.com/zowe/workshop-starter-app/commit/cbe2ceeb0b08f700813c786951b6311cd238ac93
